<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->insert([
            // Food - Nha hang 1 - Bep Cuon restaurant
        	[
                'name'=>'Bánh cuốn',
                'picture'=>'public/images/Food/BepCuon/banhCuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
            [
                'name'=>'Bánh xèo',
                'picture'=>'public/images/Food/BepCuon/banhXeo.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
            [
                'name'=>'Cháo truyền thống',
                'picture'=>'public/images/Food/BepCuon/chaoTruyenThong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
            [
                'name'=>'Há Cảo',
                'picture'=>'public/images/Food/BepCuon/haCao.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
            [
                'name'=>'Khoai tây chiên',
                'picture'=>'public/images/Food/BepCuon/khoaiTayChien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'name'=>'Lẩu cá hồi',
                'picture'=>'public/images/Food/BepCuon/lauCaHoi.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Mỳ xào hải sản',
                'picture'=>'public/images/Food/BepCuon/miXaoHaiSan.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Nấm Chiên giòn',
                'picture'=>'public/images/Food/BepCuon/namChienGion.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Top mỡ rang',
                'picture'=>'public/images/Food/BepCuon/tepMoRang.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt cuốn tròn',
                'picture'=>'public/images/Food/BepCuon/thitTron.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'name'=>'Thịt xiên nướng',
                'picture'=>'public/images/Food/BepCuon/thitXienNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Bánh xèo',
                'picture'=>'public/images/Food/BepCuon/banhXeo.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>1,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Food - Nha hang 2 - Citron restaurant
        	[
                'name'=>'Bánh cuốn',
                'picture'=>'public/images/Food/CitronRestaurant/banhCuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Gà nướng lá chanh',
                'picture'=>'public/images/Food/CitronRestaurant/gaNuonglaChanh.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Heo mồi hấp',
                'picture'=>'public/images/Food/CitronRestaurant/HeoMoiHap.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'name'=>'Heo Mồi xào Lan',
                'picture'=>'public/images/Food/CitronRestaurant/heoMoiXaolan.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Nấm chiên giòn',
                'picture'=>'public/images/Food/CitronRestaurant/namChienGion.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Top mỡ rang',
                'picture'=>'public/images/Food/CitronRestaurant/tepMoRang.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt xiên nướng',
                'picture'=>'public/images/Food/CitronRestaurant/thitXienNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>2,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Food - Nha hang 3 - Memory 
            [
                'name'=>'Bánh cuốn',
                'picture'=>'public/images/Food/Memory/banhCuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cơm chiên',
                'picture'=>'public/images/Food/Memory/comchien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Gà nướng',
                'picture'=>'public/images/Food/Memory/ganuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Mực lá hấp',
                'picture'=>'public/images/Food/Memory/mucLaHap.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu nướng',
                'picture'=>'public/images/Food/Memory/ngeunuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'name'=>'Ram cuốn',
                'picture'=>'public/images/Food/Memory/ram.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Thịt nướng',
                'picture'=>'public/images/Food/Memory/thitNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Tôm chiên giòn',
                'picture'=>'public/images/Food/Memory/tomchiengion.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Xôi cuốn rong biển',
                'picture'=>'public/images/Food/Memory/xoiCuonRongBien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Xương hầm đậu đen',
                'picture'=>'public/images/Food/Memory/xuonghamdauden.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>3,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Food - Nha hang 4 - Moc Sea Food
            [
                'name'=>'Cá chim nướng',
                'picture'=>'public/images/Food/MocSeafood/caChimNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cá trê mắm ớt',
                'picture'=>'public/images/Food/MocSeafood/caTreMamOt.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Cơm chiên trân châu',
                'picture'=>'public/images/Food/MocSeafood/comChienTranChau.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Hàu nướng',
                'picture'=>'public/images/Food/MocSeafood/hauNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu hấp sả',
                'picture'=>'public/images/Food/MocSeafood/ngeuHapSa.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Nghêu rim',
                'picture'=>'public/images/Food/MocSeafood/ngheuRim.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Óc Hương rim muối',
                'picture'=>'public/images/Food/MocSeafood/ocHuongRimMuoi.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Rau muống chiên',
                'picture'=>'public/images/Food/MocSeafood/rauMuongChien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Sa lach tròn',
                'picture'=>'public/images/Food/MocSeafood/saLachTron.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm nướng',
                'picture'=>'public/images/Food/MocSeafood/TomNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm tít hấp dầu',
                'picture'=>'public/images/Food/MocSeafood/tomTitHapDau.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>4,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Bèo',
                'picture'=>'public/images/Food/NenRestaurant/banhBeo.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Cuốn',
                'picture'=>'public/images/Food/NenRestaurant/BanhCuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Ngọt',
                'picture'=>'public/images/Food/NenRestaurant/banhNgot.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bún Chả Cá',
                'picture'=>'public/images/Food/NenRestaurant/bunChaCa.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cari',
                'picture'=>'public/images/Food/NenRestaurant/Cari.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Kem Dừa',
                'picture'=>'public/images/Food/NenRestaurant/kemdua.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Mì Vỏ Ốc',
                'picture'=>'public/images/Food/NenRestaurant/miVoOc.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt Nướng',
                'picture'=>'public/images/Food/NenRestaurant/thitNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm Hùng',
                'picture'=>'public/images/Food/NenRestaurant/tomHung.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm Rim',
                'picture'=>'public/images/Food/NenRestaurant/tomRim.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Xôi Cuộn Rong Biển',
                'picture'=>'public/images/Food/NenRestaurant/xoiCuonRongBien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>5,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],

          
  
            [
                'name'=>'Bánh Cuốn',
                'picture'=>'public/images/Food/nhàhanglangnghe/banhCuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ếch Xào Sả Ớt',
                'picture'=>'public/images/Food/nhàhanglangnghe/echXaoSaOt.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Gà Nướng Lá Chanh',
                'picture'=>'public/images/Food/nhàhanglangnghe/gaNuonglaChanh.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Heo Mọi Giả Cầy',
                'picture'=>'public/images/Food/nhàhanglangnghe/heoMoiGiaCay.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Heo Mọi Hấp',
                'picture'=>'public/images/Food/nhàhanglangnghe/HeoMoiHap.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Heo Mọi Nướng Da Giòn',
                'picture'=>'public/images/Food/nhàhanglangnghe/heoMoiNuongDaGion.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Heo Mọi Xào Lăn',
                'picture'=>'public/images/Food/nhàhanglangnghe/heoMoiXaolan.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Lòng Dồi Heo Mọi',
                'picture'=>'public/images/Food/nhàhanglangnghe/longDoiHeoMoi.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Mực Lá Hấp',
                'picture'=>'public/images/Food/nhàhanglangnghe/mucLaHap.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Xôi Gà Làng Nghệ',
                'picture'=>'public/images/Food/nhàhanglangnghe/xoigalangNghe.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Xương Hầm Đậu Đen',
                'picture'=>'public/images/Food/nhàhanglangnghe/xuonghamdauden.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>6,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Cuốn',
                'picture'=>'public/images/Food/SkyViewRestaurant/banhcuon.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Ngọt',
                'picture'=>'public/images/Food/SkyViewRestaurant/banhngot.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bò Bittet',
                'picture'=>'public/images/Food/SkyViewRestaurant/bittet.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Choocolate',
                'picture'=>'public/images/Food/SkyViewRestaurant/choocolate.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cơm Chiên',
                'picture'=>'public/images/Food/SkyViewRestaurant/comchien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Gà Nướng',
                'picture'=>'public/images/Food/SkyViewRestaurant/ganuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Trái Tim',
                'picture'=>'public/images/Food/SkyViewRestaurant/heartcake.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu Hấp',
                'picture'=>'public/images/Food/SkyViewRestaurant/ngeu.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu Nướng',
                'picture'=>'public/images/Food/SkyViewRestaurant/ngeunuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Nuôi Chiên Bơ',
                'picture'=>'public/images/Food/SkyViewRestaurant/nuoichienbo.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ốc Hương',
                'picture'=>'public/images/Food/SkyViewRestaurant/ochuong.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ram Chiên Giòn',
                'picture'=>'public/images/Food/SkyViewRestaurant/ram.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt Nướng',
                'picture'=>'public/images/Food/SkyViewRestaurant/thitnuong.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm Chiên Giòn',
                'picture'=>'public/images/Food/SkyViewRestaurant/tomchiengion.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm Hùng',
                'picture'=>'public/images/Food/SkyViewRestaurant/tomhung.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Trộn',
                'picture'=>'public/images/Food/SkyViewRestaurant/tron.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>7,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],

            [
                'name'=>'Bò Bít Tét',
                'picture'=>'public/images/Food/TheGrill/bittet.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bún Chả Cá',
                'picture'=>'public/images/Food/TheGrill/bunChaCa.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cơm Chiên',
                'picture'=>'public/images/Food/TheGrill/comchien.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Gà Nướng',
                'picture'=>'public/images/Food/TheGrill/ganuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu',
                'picture'=>'public/images/Food/TheGrill/ngeu.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Ngêu Nướng',
                'picture'=>'public/images/Food/TheGrill/ngeunuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt Nướng',
                'picture'=>'public/images/Food/TheGrill/thitNuong.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Tôm Hùng',
                'picture'=>'public/images/Food/TheGrill/tomHung.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Trộn',
                'picture'=>'public/images/Food/TheGrill/tron.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Thịt Nướng',
                'picture'=>'public/images/Food/TheGrill/thitnuong.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>1,
                'vendor_id' =>8,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Cake - Cua hang 1 - ABC
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake1.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake3.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem ABC',
                'picture'=>'public/images/Cake/ABC/cake7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>9,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Cake - Cua hang 2 - Anh Quan
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh kem anh Quân',
                'picture'=>'public/images/Cake/anhQuan/cake8.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>10,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Cake - Cua hang 3 - Ba Hưng
            [
                'name'=>'Bánh gấu',
                'picture'=>'public/images/Cake/baHung/banhGau.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh trái cây',
                'picture'=>'public/images/Cake/baHung/banhTraiCay.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bắp',
                'picture'=>'public/images/Cake/baHung/bap.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Cherry',
                'picture'=>'public/images/Cake/baHung/chery.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh cốm',
                'picture'=>'public/images/Cake/baHung/com.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh công chúa',
                'picture'=>'public/images/Cake/baHung/congchua.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh dâu',
                'picture'=>'public/images/Cake/baHung/dau.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Doreamon',
                'picture'=>'public/images/Cake/baHung/doreamon.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh full dâu',
                'picture'=>'public/images/Cake/baHung/fulldau.jpeg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Orio',
                'picture'=>'public/images/Cake/baHung/orio.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>11,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Cake - Cua hang 4 - Đồng Tiến
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cake2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cake3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cake4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cake5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cake6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/cute.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/fullbap.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh Đồng Tiến',
                'picture'=>'public/images/Cake/baHung/congchua.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>12,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Bánh PewPew',
                'picture'=>'public/images/Cake/pewpew/cake8.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>2,
                'vendor_id' =>13,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Decor - Nha hang 1 - Chino Wedding & Events
            // -----------------------------------------------------------------------------------------------------
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Đồ trang trí Chino',
                'picture'=>'public/images/Decor/Chino Wedding & Events/6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>14,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Decor - Nha hang 2 - DV Cát Tiên
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Cát Tiên',
                'picture'=>'public/images/Decor/DVCuoihoiCatTien/8.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>15
            ],
            // Decor - Nha hang 3 - Giấy Wedding
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Giấy Wedding',
                'picture'=>'public/images/Decor/GIAYWeddingDecoratrion/7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>16,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Decor - Nha hang 4 - LAROSE
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ LAROSE Wedding',
                'picture'=>'public/images/Decor/LAROSEweddingdecor/6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>17,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Lemon Wedding Decoration',
                'picture'=>'public/images/Decor/LemonWeddingDecoration/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>18,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Lemon Wedding Decoration',
                'picture'=>'public/images/Decor/LemonWeddingDecoration/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>18,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Lemon Wedding Decoration',
                'picture'=>'public/images/Decor/LemonWeddingDecoration/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>18,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Lemon Wedding Decoration',
                'picture'=>'public/images/Decor/LemonWeddingDecoration/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>18,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],[
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],[
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],[
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/5.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],[
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/6.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Dịch vụ Rin Decor',
                'picture'=>'public/images/Decor/RinDecor/7.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>3,
                'vendor_id' =>19,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
           
            // Speaker - Nha hang 1 - Hoàng Long
            [
                'name'=>'Loa Jamo C93 (Bookshelf)',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/Loa Jamo C93 (Bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Jamo C93',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/Loa Jamo C93.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Klipsch RB 81ll',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/Loa Klipsch RB 81II (bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Hoàng Long',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/loa1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Hoàng Long',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/loa2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Hoàng Long',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/loa3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Hoàng Long',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/loa4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Hoàng Long',
                'picture'=>'public/images/Speaker/AmThanhAnhSangHoangLong/loa5.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>20,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Speaker - Nha hang 2 - Danasound
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/Loa Jamo C93 (Bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/Loa Jamo C93.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/Loa Klipsch RB 81II (bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/loa1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/loa2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/loa3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/loa4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa DanaSound',
                'picture'=>'public/images/Speaker/Danasound/loa5.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>21,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Speaker - Nha hang 3 - Sea Event
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/Loa Jamo C93 (Bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/Loa Jamo C93.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/Loa Klipsch RB 81II (bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/loa1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/loa2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/loa3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/loa4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa Sea Events',
                'picture'=>'public/images/Speaker/SeaEvent/loa5.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>22,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            // Speaker - Nha hang 4 - TSK Media
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/Loa Jamo C93 (Bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/Loa Jamo C93.PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/Loa Klipsch RB 81II (bookshelf).PNG',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/loa1.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/loa2.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/loa3.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/loa4.jpg',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Loa TSk Media',
                'picture'=>'public/images/Speaker/TSKMedia/loa5.png',
                'price'=>100000,
                'discount'=>0,
                'description'=>'Great',
                'service_category_id'=>4,
                'vendor_id' =>23,
                // 'created_at' => date("Y-m-d H:i:s"),
                // 'updated_at' => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
