<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class RateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('rate')->insert([
        	[
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>5,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>6,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>7,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>8,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>9,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>10,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>11,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>12,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>13,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>14,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>15,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>16,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>17,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>18,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>19,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>20,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>21,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>22,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>23,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>24,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>25,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>26,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>27,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>28,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>29,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>30,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>31,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>32,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>33,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>34,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>35,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>36,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>37,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>38,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>39,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>40,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>41,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>42,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>43,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>44,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>45,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>46,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>47,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>48,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>49,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>50,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>51,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>4,
                'user_id'=>2,
                'product_id'=>52,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>5,
                'user_id'=>1,
                'product_id'=>53,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'quantity'=>4,
                'user_id'=>1,
                'product_id'=>54,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>55,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'quantity'=>3,
                'user_id'=>2,
                'product_id'=>56,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>2,
                'user_id'=>1,
                'product_id'=>57,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'quantity'=>3,
                'user_id'=>1,
                'product_id'=>58,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ]
        ]);
    }
}
