<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('vendors')->insert([
        	[
                'name'=>'Bếp Cuốn Đà Nẵng',
                'phone'=>'+84 70 2689 989',
                'email'=>'nhahangbepcuon@gmail.com',
                'address'=>'54 Nguyễn Văn Thoại, Ngũ Hành Sơn, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FBepCuon%2FbepCuon.PNG?alt=media&token=9cb8781d-a2d9-402e-8534-0ded183025d6',
                'description'=>'$$ - $$$, Kiểu Á, Kiểu Việt, Tốt cho sức khỏe',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
        	],
        	[
                'name'=>'Citron Restaurant',
                'phone'=>'+84 236 3938 888',
                'email'=>'nhahangcitron@gmail.com',
                'address'=>'Hoàng Sa InterContinental Danang Sun Peninsula Resort, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FCitronRestaurant%2FCitron%20Restaurant.PNG?alt=media&token=d1c53269-bfd1-4ddd-840b-186e5924c9d4',
                'description'=>'$$ - $$$, Kiểu Á, Kiểu Việt, Tốt cho sức khỏe',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Memory Lounge',
                'phone'=>'+84 511 3575 899',
                'email'=>'nhahangmemorylounge@gmail.com',
                'address'=>'7 Bạch Đằng street, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FMemory%2Fmemory.PNG?alt=media&token=99c869a1-743b-42f0-915c-eedfa7e4b46c',
                'description'=>'$$ - $$$, Kiểu Á, Kiểu Việt, Tốt cho sức khỏe',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Nhà hàng Mộc Sea Food',
                'phone'=>'+84 90 566 50 58',
                'email'=>'nhahangmocseafood@gmail.com',
                'address'=>'26 Tô Hiến Thành, Sơn Trà, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FMocSeafood%2Fmocseafood.PNG?alt=media&token=c81e9fed-9706-4ad1-b333-f4378779589b',
                'description'=>'$ - Hải sản kiểu Á, Cửa hàng thức ăn ngon',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Nén Restaurant',
                'phone'=>'+84 90 574 30 70',
                'email'=>'nenrestaurant@gmail.com',
                'address'=>'Lô 20,Mỹ Đa Tây 2 khuê Mỹ, Sơn Trà, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FNenRestaurant%2Fnenrestaurant.PNG?alt=media&token=ad09f3af-3e39-4af8-a20d-7960cafc1c58',
                'description'=>'$ - Hải sản kiểu Á, Cửa hàng thức ăn ngon',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Nhà Hàng Làng Nghệ',
                'phone'=>'+84 121 351 1119',
                'email'=>'nhahanglangnghe@gmail.com',
                'address'=>'119 Lê Lợi, P.Thạch Thang, Q. Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2Fnh%C3%A0hanglangnghe%2FnhahangLangNghe.jpg?alt=media&token=e99faaaf-b7b4-4980-964b-21d36fd1a7e1',
                'description'=>'$ - Hải sản kiểu Á, Cửa hàng thức ăn ngon',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Sky View Restaurant',
                'phone'=>'+84 236 3928 688',
                'email'=>'skyview@gmail.com',
                'address'=>'216 Võ Nguyên Giáp Tầng 20,Belle Maison Parosand P.Phước Mỹ, Q. Sơn Trà, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FSkyViewRestaurant%2FskyViewRestaurant.jpg?alt=media&token=4d882754-56fa-4f0c-9b4b-27d9275cb25d',
                'description'=>'$ - Hải sản kiểu Á, Cửa hàng thức ăn ngon',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'The Grill',
                'phone'=>'+84 236 3988 999',
                'email'=>'thegrill@gmail.com',
                'address'=>'35 Trường Sa Hòa Hải,Ngũ Hành Sơn, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Food%2FTheGrill%2Fthegrill.PNG?alt=media&token=9afe3a88-f253-4e10-9c6f-62969810fe89',
                'description'=>'$ - Hải sản kiểu Á, Cửa hàng thức ăn ngon',
                'password' => '123456',
                'service_category_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'ABC bakery',
                'phone'=>'0998289355',
                'email'=>'abccake@gmail.com',
                'address'=>'99 To Hien Thanh, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Cake%2FABC%2Flogo.jpg?alt=media&token=51357a07-3bff-4260-b609-db39f083eea0',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Anh Quân bakery',
                'phone'=>'0998289355',
                'email'=>'anhquanbakery@gmail.com',
                'address'=>'99 To Hien Thanh, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Cake%2FanhQuan%2Flogo.png?alt=media&token=27b15b1a-6d4b-4e81-8b10-8b6d7d2b806d',
                'description'=>'Chất liệu làm nên thương hiệu',
                'password' => '123456',
                'service_category_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Ba Hưng bakery',
                'phone'=>'0998289355',
                'email'=>'bahungbakery@gmail.com',
                'address'=>'99 To Hien Thanh, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Cake%2FbaHung%2Flogo.jpg?alt=media&token=ddb38fa0-9605-4e1f-b5de-6665cfe454a5',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Đồng Tiến bakery',
                'phone'=>'0998289355',
                'email'=>'dongtienbakery@gmail.com',
                'address'=>'99 To Hien Thanh, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Cake%2FdongTien%2Flogo.jpg?alt=media&token=9a0587fe-f231-4e0f-9d13-9ba9465a9347',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'PewPew',
                'phone'=>'0972689355',
                'email'=>'pewpew@gmail.com',
                'address'=>'101B Lê Hữu Trác, Da Nang',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Cake%2Fpewpew%2Flogo.jpg?alt=media&token=3ad244f6-4d20-42ff-a3ec-a4751f731af8',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Chino Wedding & Events',
                'phone'=>'090 644 7367',
                'email'=>'chinoflower99@gmail.com',
                'address'=>'55 Phạm Văn Nghị, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FChino%20Wedding%20%26%20Events%2Flogo.jpg?alt=media&token=c82ffdbf-ace3-4538-a598-6268fd498a8b',
                'description'=>'Dịch vụ chuyên nghiệp, phù hợp với từng khách hàng',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Dịch vụ Cưới Hỏi Cát Tiên',
                'phone'=>'0772 515 177',
                'email'=>'dichvucuoihoicattien@gmail.com',
                'address'=>'18 - 20 Trần Cao Vân, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FDVCuoiHoiCatTien%2Flogo.jpg?alt=media&token=c93b0301-b183-4ce5-808b-f286d8f055d4',
                'description'=>'Dịch vụ chuyên nghiệp, nhân viên tận tình',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Giấy Wedding Decoration',
                'phone'=>'0902 591 092',
                'email'=>'giay.decor@gmail.com',
                'address'=>'118 Lương Nhữ Học, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FGIAYWeddingDecoration%2F3.jpg?alt=media&token=feebbd7b-900d-4179-9c29-fe867074d9e9',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'LAROSE Wedding decor',
                'phone'=>'0929 393 404',
                'email'=>'lasore.weddingdecor@gmail.com',
                'address'=>'197 Trần Xuân Lê, Thanh Khê, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FLAROSEweddingdecor%2Flogo.jpg?alt=media&token=504aaa5e-82db-4819-8757-70bba5ee351c',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Lemon Wedding Decoration',
                'phone'=>'0929 393 379',
                'email'=>'lemonwedding@gmail.com',
                'address'=>'181 Ủy Lan Nguyên Phi, Hỉa Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FLemonWeddingDecoration%2Flogo.jpg?alt=media&token=6a09ec71-1aea-4743-bf70-85e596e4c2c9',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name'=>'Rin Decor',
                'phone'=>'0274 393 379',
                'email'=>'rin@gmail.com',
                'address'=>'181 Ủy Lan Nguyên Phi, Hỉa Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Decor%2FRinDecor%2Flogo.jpg?alt=media&token=c79cd360-47d6-474e-bd27-0af75dfa0d59',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Âm thanh ánh sáng Hoàng Long',
                'phone'=>'+84 511 382 3737',
                'email'=>'vanphong@hoanglongatas.com.vn',
                'address'=>'108 Nguyễn Thị Minh Khai, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Speaker%2FAmThanhAnhSangHoangLong%2Flogo.PNG?alt=media&token=e1c41eb2-517f-4e4f-8b89-f48bc8a52322',
                'description'=>'Dàn thiết bị đầy đủ và hiện đại',
                'password' => '123456',
                'service_category_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Âm thanh ánh sáng Danasound',
                'phone'=>'0905 699 829',
                'email'=>'dangkhoabt1@gmail.com',
                'address'=>'293/4 Nguyễn Tất Thành, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Speaker%2FDanasound%2Flogo.PNG?alt=media&token=6587c872-df82-4015-8c46-e8a8c8a9b590',
                'description'=>'Luôn cố gắng đáp ứng mọi yêu cầu từ mọi khách hàng',
                'password' => '123456',
                'service_category_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'Công ty tổ chức sự kiện Sea Event',
                'phone'=>'0968 37 4343',
                'email'=>'seaevent@gmail.com',
                'address'=>'183 Huỳnh Tấn Phát, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Speaker%2FSeaEvent%2Flogo.PNG?alt=media&token=759102ab-308d-4c56-956d-a934c146f1b6',
                'description'=>'Phục vụ tận nơi - thân thiện',
                'password' => '123456',
                'service_category_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        	[
                'name'=>'TSK Media - Thuê âm thanh ánh sáng',
                'phone'=>'0236 350 1168',
                'email'=>'tskmediadn@gmail.com',
                'address'=>'60 Trần Quý Cáp, Hải Châu, Đà Nẵng',
                'avatar'=>'https://firebasestorage.googleapis.com/v0/b/upload-queen.appspot.com/o/Speaker%2FTSKMedia%2Flogo.PNG?alt=media&token=b65e0e2b-b8a8-4b8d-8684-84ff515b1d27',
                'description'=>'Làm việc nhanh nhẹn, âm thanh ánh sáng chất lượng đạt chuẩn',
                'password' => '123456',
                'service_category_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ]
            ]);
    }
}
